= Software Architecture Documentation Example with arc42 and C4 Model

This example shows how to use https://arc42.org/[arc42] in combination with the https://c4model.com/[C4 model] with the Documentation as Code technique.

Technologies involved:

* https://arc42.org/[arc42] to get the structure for the software architecture documentation
* https://c4model.com/[C4 Model] an "abstraction-first" approach to diagramming software architecture, based upon abstractions that reflect how software architects and developers think about and build software.
* https://structurizr.com/dsl[Structurizr DSL] to describe the https://c4model.com/[C4 Model] of the software system
* https://github.com/structurizr/cli[Structurizr CLI] a command line utility for Structurizr to export the https://plantuml.com/[PlantUML] diagrams from the C4 Model described in the Structurizr DSL
* https://asciidoc.org/[AsciiDoc] as format to write the software architecture documentation
* https://docs.asciidoctor.org/asciidoctor[Asciidoctor] to generate the representations of the software architecture documentation written in asciidoc

== Prerequisites

=== AsciiDoctor
AsciiDoctor is a fast text processor and publishing toolchain for converting AsciiDoc content to HTML, DocBook and other formats.

=== Use the Docker Image

Docker Image: https://hub.docker.com/r/asciidoctor/docker-asciidoctor[asciidoctor/docker-asciidoctor]

[source, bash]
---
docker run -it --rm -v $PWD:/documents/ asciidoctor/docker-asciidoctor asciidoctor --version
---

https://github.com/asciidoctor/docker-asciidoctor/blob/main/README.adoc[Technical details about asciidoctor/docker-asciidoctor]

=== Local installed AsciiDoctor

Install the following AsciiDoctor packages:

* https://docs.asciidoctor.org/asciidoctor/latest/install/[Asciidoctor]
* https://docs.asciidoctor.org/diagram-extension/latest/[Asciidoctor-Diagrams]
* https://docs.asciidoctor.org/pdf-converter/latest/install/[Asciidoctor-PDF]

=== Generate PlantUML Diagrams from the C4 Model

==== With the Structurizr CLI via Docker Image

[source, bash]
----
docker run -it --rm -v $PWD:/usr/local/structurizr structurizr/cli export -w bank.dsl -format plantuml/structurizr -output diagrams
----

==== With a local installed Structurizr CLI

Download the https://github.com/structurizr/cli/releases[structurizr-cli], unzip and move it into `./bin/structurizr-cli` or use the latest Docker Image

[source, bash]
----
curl --show-error --location https://github.com/structurizr/cli/releases/download/v{selected-version}/structurizr-cli-{selected-version}.zip  -o tmp.zip && unzip -d bin/structurizr-cli/. tmp.zip && rm tmp.zip
----

Generate the diagrams from the structurizr workspace model

[source, bash]
----
./bin/structurizr-cli/structurizr.sh export -w bank.dsl -format plantuml/structurizr -output diagrams
----

== Generate the software architecture documentation representations

Generate the documentation as HTML representation

[source, bash]
----
asciidoctor -b html5 -r asciidoctor-diagram internet-banking-system.adoc
----

Generate the documentation as PDF representation

[source, bash]
----
asciidoctor -b pdf -r asciidoctor-diagram -r asciidoctor-pdf  internet-banking-system.adoc
----
